# Generated by Django 3.1.5 on 2021-09-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolls',
            options={'verbose_name': 'rolls', 'verbose_name_plural': 'rolls'},
        ),
        migrations.AlterField(
            model_name='rolls',
            name='index',
            field=models.CharField(max_length=5, verbose_name='index'),
        ),
    ]
