# Generated by Django 3.1.5 on 2021-09-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0013_auto_20210909_2027'),
        ('orders', '0003_orders_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('this_order', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
        migrations.CreateModel(
            name='ClothesInOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='amount')),
                ('items_sizes', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='nest.itemssizes')),
                ('order', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
            options={
                'verbose_name': 'produce',
                'verbose_name_plural': 'produce',
            },
        ),
    ]
