# Generated by Django 3.1.5 on 2021-07-04 13:31

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[300, 150], upload_to='icons')),
                ('image_hover', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[300, 150], upload_to='icons')),
                ('sequence', models.PositiveSmallIntegerField(default=0, verbose_name='sequence')),
            ],
            options={
                'verbose_name': 'Categories of items',
                'verbose_name_plural': 'Categories of items',
                'ordering': ('sequence',),
            },
        ),
    ]
