# Generated by Django 3.1.5 on 2021-07-11 10:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0002_auto_20210707_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieces',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[100, 100], upload_to='photos_pieces/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[300, 300], upload_to='photos/'),
        ),
    ]
