# Generated by Django 3.1.5 on 2021-07-20 17:30

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0003_auto_20210711_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cats_id',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='cats_id'),
        ),
        migrations.AddField(
            model_name='fashions',
            name='cats_id',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='cats_id'),
        ),
        migrations.AddField(
            model_name='items',
            name='cats_id',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='cats_id'),
        ),
        migrations.AddField(
            model_name='sizes',
            name='cats_id',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='cats_id'),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[300, 300], upload_to='photos_items/'),
        ),
    ]
