# Generated by Django 3.1.5 on 2021-07-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0005_produce_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produce_page',
        ),
    ]
