# Generated by Django 3.1.5 on 2021-07-23 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0006_delete_produce_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest.items')),
                ('sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest.sizes')),
            ],
            options={
                'verbose_name': 'produce',
                'verbose_name_plural': 'produce',
            },
        ),
    ]
