# Generated by Django 3.1.5 on 2021-07-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0008_auto_20210726_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pieces',
            name='items',
        ),
        migrations.RemoveField(
            model_name='pieces',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='producepage',
            name='items',
        ),
        migrations.RemoveField(
            model_name='producepage',
            name='sizes',
        ),
        migrations.AddField(
            model_name='producepage',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='sequence'),
        ),
        migrations.CreateModel(
            name='ItemsSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest.items')),
                ('sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest.sizes')),
            ],
            options={
                'verbose_name': 'items sizes',
                'verbose_name_plural': 'items sizes',
            },
        ),
        migrations.AddField(
            model_name='pieces',
            name='items_sizes',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='nest.itemssizes'),
        ),
        migrations.AddField(
            model_name='producepage',
            name='items_sizes',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='nest.itemssizes'),
        ),
    ]
