# Generated by Django 3.1.5 on 2021-09-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0012_auto_20210821_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.FileField(blank=True, upload_to='photos_items/'),
        ),
    ]
